services:
  rustwho:
    image: ubermetroid/rustwho:latest
    build: .
    container_name: rustwho
    restart: unless-stopped
    ports:
      - ${PORT:-4404}:4404
    environment:
      - SITE_TITLE=${SITE_TITLE:-RustWho}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-*}